// /team/reference — plain-language reference for every framework, technique and concept used or cited in CTO360.
// Each card: a small diagram, the core idea, the question it answers, and where CTO360 applies it (if it does).
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Search } from 'lucide-react'
import { PageHeader } from '../../components/ui'

type Vis =
  | { t: 'quad'; q: [string, string, string, string]; x?: string; y?: string; center?: string }
  | { t: 'steps'; items: string[]; loop?: boolean }
  | { t: 'stack'; items: [string, number][] }
  | { t: 'layers'; items: string[]; up?: boolean }
  | { t: 'hub'; center: string; items: string[] }
  | { t: 'chain'; items: string[]; sub?: string }
  | { t: 'grid'; cols: number; items: string[]; big?: boolean }
  | { t: 'curve'; kind: 'bell-chasm' | 's' | 'hockey' | 'normal' | 'queue' | 'spike' | 'two-dist' | 'pareto' | 'tornado' | 'glide' | 'cashflow' | 'forecast' | 'breakeven' | 'horizons' | 'heat' }
interface Ref { name: string; cat: Cat; core: string; when: string; vis: Vis; applied?: [string, string] }
type Cat = 'Strategy' | 'Growth & portfolio' | 'Execution' | 'Innovation & customer' | 'Platforms' | 'Organisation & change' | 'Decision-making' | 'Risk & governance' | 'Finance & investment' | 'Operations' | 'Analytics technique'

const W = (o: string, tab: string) => `/team/${o}?tab=${tab}`
const REFS: Ref[] = [
  // ── Strategy ──
  { name: 'SWOT', cat: 'Strategy', core: 'Lists internal Strengths and Weaknesses next to external Opportunities and Threats, so strategy builds on strengths and guards against threats.', when: 'Where are we today?', vis: { t: 'quad', q: ['Strengths', 'Weaknesses', 'Opportunities', 'Threats'], x: 'helpful ← → harmful', y: 'internal ↑ ↓ external' } },
  { name: 'PESTLE', cat: 'Strategy', core: 'Scans six outside forces — Political, Economic, Social, Technological, Legal, Environmental — that can change the business no matter what we do internally.', when: "What's happening outside?", vis: { t: 'grid', cols: 6, items: ['P', 'E', 'S', 'T', 'L', 'E'], big: true } },
  { name: 'Porter Five Forces', cat: 'Strategy', core: 'Industry profit depends on five pressures: rivalry, threat of new entrants, buyer power, supplier power and substitutes. Strong forces squeeze margins.', when: 'How attractive is this industry?', vis: { t: 'hub', center: 'Rivalry', items: ['New entrants', 'Suppliers', 'Buyers', 'Substitutes'] } },
  { name: 'Porter Generic Strategies', cat: 'Strategy', core: 'Win either by lowest cost or by being different, across the broad market or a narrow focus. Being "stuck in the middle" rarely works.', when: 'How will we compete?', vis: { t: 'quad', q: ['Cost leadership', 'Differentiation', 'Cost focus', 'Differentiation focus'], x: 'low cost ← → unique', y: 'broad ↑ ↓ narrow' } },
  { name: 'Porter Value Chain', cat: 'Strategy', core: 'Breaks the business into primary activities (from inbound to service) and support activities, to see where technology adds value or cost.', when: 'Where does technology create value?', vis: { t: 'chain', items: ['Inbound', 'Operations', 'Outbound', 'Marketing & sales', 'Service'], sub: 'Support: infrastructure · HR · technology · procurement' }, applied: ['/domain/manufacturing/process', 'Process Intelligence'] },
  { name: 'VRIO', cat: 'Strategy', core: 'A capability gives lasting advantage only if it is Valuable, Rare, hard to Imitate and the firm is Organised to exploit it.', when: 'Which capabilities really give us an edge?', vis: { t: 'steps', items: ['Valuable?', 'Rare?', 'Inimitable?', 'Organised?', 'Sustained advantage'] } },
  { name: 'Mintzberg 5Ps', cat: 'Strategy', core: 'Strategy is more than a plan: it is also a ploy, a pattern of actual behaviour, a market position and a shared perspective.', when: 'Is our stated strategy what we actually do?', vis: { t: 'hub', center: 'Strategy', items: ['Plan', 'Ploy', 'Pattern', 'Position', 'Perspective'] } },
  { name: 'Strategy quality tests (Rumelt)', cat: 'Strategy', core: 'A good strategy is consistent with itself, consonant with the environment, creates advantage, and is feasible with the resources available.', when: 'Is this strategy any good?', vis: { t: 'grid', cols: 2, items: ['Consistency', 'Consonance', 'Advantage', 'Feasibility'] } },
  // ── Growth & portfolio ──
  { name: 'Ansoff Matrix', cat: 'Growth & portfolio', core: 'Four growth routes: sell more of the same (penetration), new products, new markets, or both (diversification — highest risk).', when: 'Where should we grow?', vis: { t: 'quad', q: ['Market penetration', 'Product development', 'Market development', 'Diversification'], x: 'existing ← products → new', y: 'existing ↑ markets ↓ new' } },
  { name: 'BCG Growth-Share Matrix', cat: 'Growth & portfolio', core: 'Sorts products by market growth and share: invest in Stars, milk Cash cows, decide on Question marks, exit Dogs.', when: 'Where should money go across the portfolio?', vis: { t: 'quad', q: ['Stars', 'Question marks', 'Cash cows', 'Dogs'], x: 'high ← share → low', y: 'high ↑ growth ↓ low' } },
  { name: 'Blue Ocean Strategy', cat: 'Growth & portfolio', core: 'Create uncontested market space by Eliminating, Reducing, Raising and Creating factors instead of fighting rivals on the same terms.', when: 'Can we stop competing head-on?', vis: { t: 'grid', cols: 2, items: ['Eliminate', 'Raise', 'Reduce', 'Create'] } },
  { name: 'Three Horizons', cat: 'Growth & portfolio', core: 'Balance investment across today’s core (H1), emerging businesses (H2) and future options (H3) — a common guide is 70 / 20 / 10.', when: 'Are we investing for today and tomorrow?', vis: { t: 'curve', kind: 'horizons' }, applied: [W('suman', 'frameworks'), 'Suman'] },
  { name: 'Run-Grow-Transform', cat: 'Growth & portfolio', core: 'Splits technology spend into running the business, growing it and transforming it; too much "run" starves change.', when: 'Is spend balanced between keeping the lights on and change?', vis: { t: 'stack', items: [['Run', 60], ['Grow', 25], ['Transform', 15]] }, applied: [W('santhosh', 'frameworks'), 'Santhosh'] },
  { name: 'Value vs Effort matrix', cat: 'Growth & portfolio', core: 'Plots initiatives by value and effort: do quick wins first, plan big bets, fill gaps with fill-ins, avoid money pits.', when: 'What should we do first?', vis: { t: 'quad', q: ['Quick wins', 'Big bets', 'Fill-ins', 'Money pits'], x: 'low ← effort → high', y: 'high ↑ value ↓ low' }, applied: [W('suman', 'portfolio'), 'Suman'] },
  // ── Execution ──
  { name: 'Balanced Scorecard', cat: 'Execution', core: 'Tracks strategy through four perspectives — financial, customer, internal process, learning & growth — so money is not the only measure.', when: 'Are we executing in a balanced way?', vis: { t: 'grid', cols: 2, items: ['Financial', 'Customer', 'Internal process', 'Learning & growth'] }, applied: [W('ram', 'frameworks'), 'Ram'] },
  { name: 'OKRs', cat: 'Execution', core: 'An inspiring Objective with 2–5 measurable Key Results; progress is scored, not assumed.', when: 'How do we turn goals into measurable results?', vis: { t: 'layers', items: ['Objective', 'Key result 1 · 0.7', 'Key result 2 · 0.4', 'Key result 3 · 1.0'] }, applied: [W('ram', 'transformation'), 'Transformation tabs'] },
  { name: 'Strategy Maps', cat: 'Execution', core: 'Draws cause-and-effect: capabilities enable processes, processes delight customers, customers drive financial results.', when: 'How do our actions add up to outcomes?', vis: { t: 'layers', items: ['Financial results', 'Customer value', 'Internal processes', 'People & capabilities'], up: true } },
  { name: 'Stage-Gate', cat: 'Execution', core: 'Work moves through stages; at each gate a named person decides go, hold or stop based on evidence.', when: 'How do we control progress from idea to scale?', vis: { t: 'steps', items: ['Idea', 'PoC', 'Pilot', 'Production', 'Scale'] }, applied: [W('suman', 'portfolio'), 'Suman'] },
  // ── Innovation & customer ──
  { name: 'Lean Startup', cat: 'Innovation & customer', core: 'Build the smallest test, measure real behaviour, learn — then pivot or persevere. Speed of learning beats perfect plans.', when: 'How do we test an idea cheaply?', vis: { t: 'steps', items: ['Build', 'Measure', 'Learn'], loop: true } },
  { name: 'Design Thinking', cat: 'Innovation & customer', core: 'Start from people: understand them, define the real problem, generate ideas, prototype quickly and test with users.', when: 'What problem are we really solving?', vis: { t: 'steps', items: ['Empathise', 'Define', 'Ideate', 'Prototype', 'Test'] } },
  { name: 'Jobs-to-be-Done', cat: 'Innovation & customer', core: 'Customers "hire" a product to get a job done in a situation; design for the job and the outcome, not the feature.', when: 'What outcome does the customer actually want?', vis: { t: 'chain', items: ['Situation', 'Job to be done', 'Desired outcome'] } },
  { name: 'Value Proposition Canvas', cat: 'Innovation & customer', core: 'Matches customer jobs, pains and gains with your products, pain relievers and gain creators — fit means they line up.', when: 'Does our offer fit what customers need?', vis: { t: 'grid', cols: 3, items: ['Products', 'Pain relievers', 'Gain creators', 'Customer jobs', 'Pains', 'Gains'] } },
  { name: 'Business Model Canvas', cat: 'Innovation & customer', core: 'One page with nine blocks showing how an organisation creates, delivers and captures value.', when: 'How will this make (or save) money?', vis: { t: 'grid', cols: 5, items: ['Partners', 'Activities', 'Value', 'Relations', 'Segments', 'Resources', '', '', 'Channels', '', 'Costs', '', '', 'Revenue', ''] }, applied: [W('suman', 'onboard'), 'Suman · Onboard'] },
  { name: 'Diffusion of Innovations', cat: 'Innovation & customer', core: 'People adopt in waves — innovators, early adopters, early majority, late majority, laggards. Adoption speeds up with relative advantage, compatibility, simplicity, trialability and observability.', when: 'Who will adopt, and what slows them?', vis: { t: 'curve', kind: 'bell-chasm' }, applied: [W('suman', 'frameworks'), 'Suman'] },
  { name: 'Crossing the Chasm', cat: 'Innovation & customer', core: 'There is a gap between enthusiastic early adopters and the pragmatic majority; cross it with a reference customer and a complete solution.', when: 'Why do pilots not scale?', vis: { t: 'curve', kind: 'bell-chasm' }, applied: [W('suman', 'frameworks'), 'Suman'] },
  // ── Platforms ──
  { name: 'Pipeline vs Platform', cat: 'Platforms', core: 'A pipeline creates value step by step inside the firm; a platform connects producers and consumers and lets them create value with each other.', when: 'Should this be a workflow or a reusable capability?', vis: { t: 'chain', items: ['Make', 'Sell', 'Deliver'], sub: 'Platform: producers ⇄ platform ⇄ consumers' } },
  { name: 'Network Effects', cat: 'Platforms', core: 'Each new user (or data point, or partner) makes the product more valuable for everyone, so value grows faster than size.', when: 'Will growth compound?', vis: { t: 'curve', kind: 'hockey' } },
  { name: 'Winner-Take-All', cat: 'Platforms', core: 'Strong network effects, high switching costs and little differentiation push markets towards one dominant player.', when: 'Will this market concentrate?', vis: { t: 'stack', items: [['Leader', 70], ['#2', 20], ['Rest', 10]] } },
  { name: 'Open vs Closed architecture', cat: 'Platforms', core: 'Closed: provider-managed models and services (fast, less control). Open: open-weight or self-hosted (control, more effort).', when: 'Do we buy the AI as a service or run our own?', vis: { t: 'grid', cols: 2, items: ['Closed · speed, vendor-managed', 'Open · control, self-hosted'] } },
  { name: 'Modularity × Coordination', cat: 'Platforms', core: 'How much the parts can be separated vs how much they must be coordinated decides platform, ecosystem or vertical integration.', when: 'Should we integrate or orchestrate?', vis: { t: 'quad', q: ['Ecosystem', 'Platform', 'Market', 'Vertical integration'], x: 'low ← coordination → high', y: 'high ↑ modularity ↓ low' } },
  { name: 'XaaS (anything as a service)', cat: 'Platforms', core: 'Consume capabilities as services — infrastructure, platform, software, AI — paying for use instead of owning; shifts CAPEX to OPEX.', when: 'Buy, build or subscribe?', vis: { t: 'layers', items: ['AI as a service', 'Software (SaaS)', 'Platform (PaaS)', 'Infrastructure (IaaS)'] } },
  // ── Organisation & change ──
  { name: 'McKinsey 7S', cat: 'Organisation & change', core: 'Seven elements must fit together: strategy, structure, systems (hard) and shared values, style, staff, skills (soft).', when: 'Is the organisation aligned to the strategy?', vis: { t: 'hub', center: 'Shared values', items: ['Strategy', 'Structure', 'Systems', 'Style', 'Staff', 'Skills'] } },
  { name: 'Galbraith Star Model', cat: 'Organisation & change', core: 'Organisation design has five levers — strategy, structure, processes, rewards and people — that must point the same way.', when: 'How should we organise?', vis: { t: 'hub', center: 'Design', items: ['Strategy', 'Structure', 'Processes', 'Rewards', 'People'] } },
  { name: 'Operating Model Canvas', cat: 'Organisation & change', core: 'Shows how strategy becomes daily work: value chain, organisation, locations, information, suppliers and management system.', when: 'What operating capabilities do we need?', vis: { t: 'grid', cols: 3, items: ['Value chain', 'Organisation', 'Locations', 'Information', 'Suppliers', 'Management'] }, applied: ['/cto/operating-model', 'Operating model page'] },
  { name: 'Kotter 8 steps', cat: 'Organisation & change', core: 'Large change needs urgency, a coalition, a vision, broad buy-in, removed barriers, quick wins, sustained momentum and anchoring in culture.', when: 'How do we lead organisation-wide change?', vis: { t: 'steps', items: ['Urgency', 'Coalition', 'Vision', 'Volunteers', 'Barriers', 'Wins', 'Accelerate', 'Anchor'] }, applied: ['/team', 'Team page'] },
  { name: 'ADKAR', cat: 'Organisation & change', core: 'Individuals change in order: Awareness, Desire, Knowledge, Ability, Reinforcement. They stall at the first missing step.', when: 'Why are people not adopting?', vis: { t: 'steps', items: ['Awareness', 'Desire', 'Knowledge', 'Ability', 'Reinforcement'] }, applied: ['/team', 'Team page'] },
  { name: 'Lewin change model', cat: 'Organisation & change', core: 'Unfreeze the old way, make the change, then refreeze so the new way sticks.', when: 'Where are we in the change?', vis: { t: 'steps', items: ['Unfreeze', 'Change', 'Refreeze'] }, applied: [W('pankaj', 'production'), 'Pankaj'] },
  { name: 'Theory E vs Theory O', cat: 'Organisation & change', core: 'E = change for economic value (cost, restructuring, top-down); O = change by building capability and culture (participative). Lasting change combines both.', when: 'Are we balancing value and capability?', vis: { t: 'grid', cols: 2, items: ['E · economic value', 'O · organisational capability'] } },
  // ── Decision-making ──
  { name: 'Cynefin', cat: 'Decision-making', core: 'Match the approach to the problem: Clear (best practice), Complicated (expert analysis), Complex (experiment), Chaotic (act first).', when: 'How should we decide on this problem?', vis: { t: 'quad', q: ['Complex · probe', 'Complicated · analyse', 'Chaotic · act', 'Clear · categorise'], center: 'Confusion' }, applied: [W('ram', 'frameworks'), 'Ram'] },
  { name: 'RAPID', cat: 'Decision-making', core: 'Names decision roles: Recommend, Agree, Perform, Input and the one person who Decides.', when: 'Who decides?', vis: { t: 'grid', cols: 5, items: ['R', 'A', 'P', 'I', 'D'], big: true }, applied: [W('ram', 'frameworks'), 'Ram'] },
  { name: 'OODA loop', cat: 'Decision-making', core: 'Observe → Orient → Decide → Act, repeated faster than the situation changes.', when: 'How do we decide quickly?', vis: { t: 'steps', items: ['Observe', 'Orient', 'Decide', 'Act'], loop: true }, applied: [W('ram', 'frameworks'), 'Ram'] },
  { name: 'RACI', cat: 'Decision-making', core: 'For each task: who is Responsible (does it), Accountable (owns it), Consulted and Informed.', when: 'Who owns what?', vis: { t: 'grid', cols: 4, items: ['R', 'A', 'C', 'I'], big: true }, applied: ['/team', 'Team page'] },
  { name: 'TEDIF · AI recommends, humans decide', cat: 'Decision-making', core: 'The project’s framework: AI gathers signals and recommends; a named person decides at a gate; every step is audited.', when: 'How do we use AI safely in decisions?', vis: { t: 'steps', items: ['Signals', 'AI recommends', 'Human decides', 'Audit trail'] }, applied: ['/decision-center', 'Decision Center'] },
  // ── Risk & governance ──
  { name: 'Three Lines Model', cat: 'Risk & governance', core: 'Risk is owned by management (1st line), overseen by risk and compliance (2nd), and independently assured by internal audit (3rd).', when: 'Who owns, oversees and assures risk?', vis: { t: 'layers', items: ['Governing body', '3rd · internal audit (assure)', '2nd · risk & compliance (oversee)', '1st · management (own)'] }, applied: [W('vaibhav', 'frameworks'), 'Vaibhav'] },
  { name: 'Risk matrix / heat map', cat: 'Risk & governance', core: 'Scores each risk by likelihood × impact so the few severe ones get attention first.', when: 'Which risks matter most?', vis: { t: 'curve', kind: 'heat' }, applied: ['/domain/banking/vanta?tab=heatmap', 'Vanta page'] },
  { name: 'Risk process', cat: 'Risk & governance', core: 'A continuous loop: identify risks, assess them, intervene with controls, and govern (monitor and report).', when: 'How do we manage AI and tech risk continuously?', vis: { t: 'steps', items: ['Identify', 'Assess', 'Intervene', 'Govern'], loop: true }, applied: [W('vaibhav', 'models'), 'Vaibhav'] },
  { name: 'NIST AI RMF / ISO 42001', cat: 'Risk & governance', core: 'AI risk frameworks: govern, map the context, measure risks (bias, drift, robustness) and manage them. CTO360 follows them in spirit only.', when: 'Is our AI trustworthy?', vis: { t: 'hub', center: 'Govern', items: ['Map', 'Measure', 'Manage'] }, applied: [W('vaibhav', 'models'), 'Model register'] },
  { name: 'ESG', cat: 'Risk & governance', core: 'Environmental, Social and Governance performance — for technology: energy and carbon, responsible AI and data, and governance.', when: 'Is our technology sustainable and responsible?', vis: { t: 'grid', cols: 3, items: ['E', 'S', 'G'], big: true } },
  { name: 'Maturity model (L1–L5)', cat: 'Risk & governance', core: 'Capability grows in levels — from visible, to managed, standardised, measured and continuously optimised. CTO360 uses it for management, not certification.', when: 'How mature are we, and what is next?', vis: { t: 'steps', items: ['L1', 'L2', 'L3', 'L4', 'L5'] }, applied: ['/domain/banking/decisions?tab=maturity', 'Maturity view'] },
  // ── Finance & investment ──
  { name: 'NPV · IRR · payback', cat: 'Finance & investment', core: 'NPV = today’s value of future cash flows minus the cost; IRR = the return that makes NPV zero; payback = time to earn the money back.', when: 'Is this investment worth it?', vis: { t: 'curve', kind: 'cashflow' }, applied: [W('santhosh', 'invest'), 'Santhosh'] },
  { name: 'TCO (total cost of ownership)', cat: 'Finance & investment', core: 'The full cost over the life of a system — build or buy, plus years of running, support and upgrades — not just the purchase price.', when: 'What does it really cost?', vis: { t: 'stack', items: [['Build', 67], ['5-year run', 33]] }, applied: [W('santhosh', 'frameworks'), 'Santhosh'] },
  { name: 'Sensitivity analysis (tornado)', cat: 'Finance & investment', core: 'Change one assumption at a time and see how far the result moves; the widest bar is the assumption to watch.', when: 'Which assumption matters most?', vis: { t: 'curve', kind: 'tornado' }, applied: [W('santhosh', 'frameworks'), 'Santhosh'] },
  { name: 'DuPont · ROIC', cat: 'Finance & investment', core: 'DuPont splits return on equity into profit margin × asset turnover × leverage; ROIC shows the return on all capital invested.', when: 'Where do returns come from?', vis: { t: 'layers', items: ['ROE', '= margin × asset turnover × leverage', 'ROIC = operating profit after tax ÷ invested capital'] } },
  { name: 'Cost-volume-profit (CVP)', cat: 'Finance & investment', core: 'Break-even is where revenue covers fixed plus variable costs; operating leverage shows how fast profit grows after that.', when: 'How much volume do we need?', vis: { t: 'curve', kind: 'breakeven' } },
  { name: 'TBM (Technology Business Management)', cat: 'Finance & investment', core: 'Allocates technology costs from cost pools to IT towers to services and business units, so everyone sees what technology costs.', when: 'Where does technology money go?', vis: { t: 'chain', items: ['Cost pools', 'IT towers', 'Services', 'Business units'] }, applied: [W('santhosh', 'capex'), 'Santhosh'] },
  { name: 'FinOps', cat: 'Finance & investment', core: 'Cloud financial management as a loop: inform (see costs), optimise (rightsize, remove waste), operate (budgets and alerts).', when: 'Is our cloud spend under control?', vis: { t: 'steps', items: ['Inform', 'Optimise', 'Operate'], loop: true }, applied: [W('santhosh', 'finops'), 'Santhosh'] },
  // ── Operations ──
  { name: 'Theory of Constraints', cat: 'Operations', core: 'A system is limited by one bottleneck. Identify it, exploit it, subordinate everything else to it, elevate it — then find the next one.', when: 'What really limits us?', vis: { t: 'steps', items: ['Identify', 'Exploit', 'Subordinate', 'Elevate', 'Repeat'], loop: true }, applied: [W('pankaj', 'frameworks'), 'Pankaj'] },
  { name: 'ITIL problem management', cat: 'Operations', core: 'Incidents are restored fast; repeated incidents become a problem, the cause becomes a known error, and a change fixes it for good.', when: 'How do we stop repeat incidents?', vis: { t: 'chain', items: ['Incident', 'Problem', 'Known error', 'Change'] }, applied: [W('pankaj', 'erp'), 'Pankaj'] },
  { name: '5 Whys', cat: 'Operations', core: 'Ask "why?" about five times to move from the symptom to the root cause.', when: 'What is the real cause?', vis: { t: 'layers', items: ['Why? → symptom', 'Why? → cause', 'Why? → deeper cause', 'Why? → process gap', 'Root cause'] }, applied: [W('pankaj', 'erp'), 'Pankaj'] },
  { name: 'SRE error budget', cat: 'Operations', core: 'An SLO of 99.95% allows 0.05% downtime — the budget. While budget remains, ship changes; when it is spent, fix reliability first.', when: 'How reliable is reliable enough?', vis: { t: 'stack', items: [['Used', 40], ['Remaining', 60]] }, applied: [W('pankaj', 'erp'), 'Pankaj'] },
  { name: 'Queueing (M/M/1, Little’s law)', cat: 'Operations', core: 'Response time = service time ÷ (1 − utilisation). Above about 80% busy, waiting time explodes — add capacity before the peak.', when: 'Why do systems slow down at peak?', vis: { t: 'curve', kind: 'queue' }, applied: [W('pankaj', 'peaks'), 'Pankaj'] },
  // ── Analytics techniques ──
  { name: 'Pareto (80/20)', cat: 'Analytics technique', core: 'A few causes create most of the effect. Sort causes by size and fix the top few first.', when: 'Which few causes matter most?', vis: { t: 'curve', kind: 'pareto' }, applied: [W('pankaj', 'erp'), 'Pankaj'] },
  { name: 'Monte Carlo simulation', cat: 'Analytics technique', core: 'Run thousands of what-if trials with uncertain inputs to get a range of outcomes — downside (P10), likely (P50), upside (P90).', when: 'How confident are we in the number?', vis: { t: 'curve', kind: 'normal' }, applied: [W('suman', 'roi'), 'Suman'] },
  { name: 'Holt / Holt-Winters forecasting', cat: 'Analytics technique', core: 'Exponential smoothing that tracks level and trend (and seasonality) to project the next months.', when: 'Where is this metric heading?', vis: { t: 'curve', kind: 'forecast' }, applied: [W('pankaj', 'capacity'), 'Pankaj · capacity'] },
  { name: 'EWMA anomaly detection', cat: 'Analytics technique', core: 'Keeps a smoothed average of recent values and flags points that jump far beyond normal variation (e.g. 3 standard deviations).', when: 'Is this spike unusual?', vis: { t: 'curve', kind: 'spike' }, applied: [W('santhosh', 'budget'), 'Santhosh · cloud'] },
  { name: 'PSI (population stability index)', cat: 'Analytics technique', core: 'Compares a model’s training data distribution with today’s; above 0.25 means the world has drifted and the model needs revalidation.', when: 'Is the AI model still valid?', vis: { t: 'curve', kind: 'two-dist' }, applied: [W('vaibhav', 'models'), 'Vaibhav'] },
  { name: 'S-curve adoption', cat: 'Analytics technique', core: 'Adoption starts slowly, accelerates, then levels off — used to ramp benefits realistically after go-live.', when: 'When will the value arrive?', vis: { t: 'curve', kind: 's' }, applied: [W('suman', 'roi'), 'Suman'] },
  { name: 'Glide path · progress · ETA', cat: 'Analytics technique', core: 'Progress = share of the gap from baseline to target already closed; compared with the share of time used, it shows ahead / on track / behind.', when: 'Are we transforming fast enough?', vis: { t: 'curve', kind: 'glide' }, applied: [W('ram', 'transformation'), 'Every workspace'] },
  { name: 'Event correlation', cat: 'Analytics technique', core: 'Links signals from different tools through shared record IDs and time windows, so one root issue is seen as one story, not seven alerts.', when: 'Are these alerts the same problem?', vis: { t: 'chain', items: ['Signals', 'Shared IDs', 'One story', 'Decision'] }, applied: [W('ram', 'agents'), 'Ram'] },
]
const CATS: Cat[] = ['Strategy', 'Growth & portfolio', 'Execution', 'Innovation & customer', 'Platforms', 'Organisation & change', 'Decision-making', 'Risk & governance', 'Finance & investment', 'Operations', 'Analytics technique']

// ── Mini visuals (plain HTML / SVG, design tokens only) ──
const box = 'rounded-md border border-brand-100 bg-brand-50 text-brand-900 flex items-center justify-center text-center leading-tight'
function Visual({ v }: { v: Vis }) {
  if (v.t === 'quad') return (
    <div className="relative">
      <div className="grid grid-cols-2 gap-1 text-[10.5px] font-medium">{v.q.map((x, i) => <div key={i} className={`${box} h-11 px-1 ${i === 0 ? 'bg-brand-100' : ''}`}>{x}</div>)}</div>
      {v.center && <div className="absolute inset-0 flex items-center justify-center pointer-events-none"><span className="text-[9.5px] bg-white border border-line rounded px-1">{v.center}</span></div>}
      {(v.x || v.y) && <div className="flex justify-between text-[9px] text-ink-4 mt-0.5"><span>{v.y}</span><span>{v.x}</span></div>}
    </div>
  )
  if (v.t === 'steps') return (
    <div className="flex items-center gap-0.5 flex-wrap">{v.items.map((x, i) => <span key={i} className="flex items-center gap-0.5"><span className={`${box} h-8 px-1.5 text-[10px] font-medium`}>{x}</span>{(i < v.items.length - 1 || v.loop) && <span className="text-ink-4 text-[11px]">{i === v.items.length - 1 ? '↺' : '→'}</span>}</span>)}</div>
  )
  if (v.t === 'stack') return (
    <div><div className="flex h-9 rounded-md overflow-hidden gap-0.5">{v.items.map(([l, p], i) => <div key={l} className="flex items-center justify-center text-[10px] font-semibold text-white" style={{ width: `${p}%`, background: ['#0f2747', '#2563eb', '#86b6ef'][i % 3] }}>{p >= 15 ? `${l} ${p}%` : ''}</div>)}</div>
      <div className="flex gap-3 text-[9.5px] text-ink-3 mt-1">{v.items.map(([l, p]) => <span key={l}>{l} {p}%</span>)}</div></div>
  )
  if (v.t === 'layers') return <div className="space-y-0.5">{v.items.map((x, i) => <div key={i} className={`${box} h-6 text-[10px] ${i === 0 ? 'bg-brand-100 font-semibold' : ''}`} style={{ marginLeft: v.up ? 0 : i * 6, marginRight: v.up ? 0 : i * 6 }}>{v.up && i > 0 ? '↑ ' : ''}{x}</div>)}</div>
  if (v.t === 'hub') {
    const n = v.items.length
    return (
      <svg viewBox="0 0 200 110" className="w-full h-[110px]" role="img" aria-label={`${v.center} connected to ${v.items.join(', ')}`}>
        {v.items.map((x, i) => { const a = (i / n) * 2 * Math.PI - Math.PI / 2; const cx = 100 + Math.cos(a) * 72, cy = 55 + Math.sin(a) * 40; return <g key={x}><line x1={100} y1={55} x2={cx} y2={cy} stroke="#93c5fd" /><rect x={cx - 30} y={cy - 8} width={60} height={16} rx={4} fill="#eff6ff" stroke="#dbeafe" /><text x={cx} y={cy + 3.5} textAnchor="middle" fontSize={8.5} fill="#0f2747">{x}</text></g> })}
        <rect x={68} y={45} width={64} height={20} rx={5} fill="#0f2747" /><text x={100} y={58.5} textAnchor="middle" fontSize={9} fill="white" fontWeight={600}>{v.center}</text>
      </svg>
    )
  }
  if (v.t === 'chain') return (
    <div><div className="flex gap-0.5">{v.items.map((x, i) => <div key={i} className={`${box} flex-1 h-10 text-[10px] font-medium px-0.5`} style={{ clipPath: i < v.items.length - 1 ? 'polygon(0 0, 88% 0, 100% 50%, 88% 100%, 0 100%)' : undefined }}>{x}</div>)}</div>
      {v.sub && <div className="text-[9.5px] text-ink-3 mt-1">{v.sub}</div>}</div>
  )
  if (v.t === 'grid') return <div className="grid gap-1" style={{ gridTemplateColumns: `repeat(${v.cols}, minmax(0, 1fr))` }}>{v.items.map((x, i) => <div key={i} className={`${x ? box : ''} ${v.big ? 'h-11 text-lg font-bold' : 'h-9 text-[10px] font-medium px-0.5'}`}>{x}</div>)}</div>
  return <Curve kind={v.kind} />
}
function Curve({ kind }: { kind: Extract<Vis, { t: 'curve' }>['kind'] }) {
  const P = (f: (x: number) => number, n = 40) => Array.from({ length: n + 1 }, (_, i) => { const x = i / n; return `${10 + x * 180},${100 - f(x) * 85}` }).join(' ')
  const line = (pts: string, c = '#2563eb', dash?: string) => <polyline points={pts} fill="none" stroke={c} strokeWidth={2} strokeDasharray={dash} />
  const axes = <><line x1={10} y1={100} x2={190} y2={100} stroke="#cbd5e1" /><line x1={10} y1={10} x2={10} y2={100} stroke="#cbd5e1" /></>
  const svg = (children: React.ReactNode, label: string) => <svg viewBox="0 0 200 110" className="w-full h-[110px]" role="img" aria-label={label}>{children}</svg>
  switch (kind) {
    case 'bell-chasm': return svg(<>{axes}{line(P((x) => Math.exp(-((x - 0.5) ** 2) / 0.05)))}<line x1={10 + 0.2 * 180} y1={12} x2={10 + 0.2 * 180} y2={100} stroke="#dc2626" strokeDasharray="3 3" /><text x={10 + 0.2 * 180 + 3} y={20} fontSize={8} fill="#b91c1c">chasm</text>{['Innov.', 'Early', 'Early maj.', 'Late maj.', 'Lag.'].map((l, i) => <text key={l} x={[14, 38, 78, 122, 168][i]} y={108} fontSize={7} fill="#64748b">{l}</text>)}</>, 'Adoption bell curve with the chasm after early adopters')
    case 's': return svg(<>{axes}{line(P((x) => 1 / (1 + Math.exp(-12 * (x - 0.5)))))}<text x={14} y={20} fontSize={8} fill="#64748b">adoption</text></>, 'S-shaped adoption curve')
    case 'hockey': return svg(<>{axes}{line(P((x) => x ** 2.6))}{line(P((x) => x * 0.6), '#94a3b8', '4 3')}<text x={120} y={30} fontSize={8} fill="#2563eb">value with network effects</text><text x={160} y={84} fontSize={8} fill="#64748b">linear</text></>, 'Value grows faster than users with network effects')
    case 'normal': return svg(<>{axes}{Array.from({ length: 15 }, (_, i) => { const x = (i + 0.5) / 15, h = Math.exp(-((x - 0.5) ** 2) / 0.035) * 80; return <rect key={i} x={12 + i * 12} y={100 - h} width={10} height={h} fill={i < 3 || i > 11 ? '#86b6ef' : '#2563eb'} rx={1} /> })}<text x={20} y={20} fontSize={8} fill="#64748b">P10</text><text x={92} y={16} fontSize={8} fill="#0f2747">P50</text><text x={160} y={20} fontSize={8} fill="#64748b">P90</text></>, 'Monte Carlo distribution of outcomes')
    case 'queue': return svg(<>{axes}{line(P((x) => Math.min(1, 0.06 / (1 - x * 0.97))))}<line x1={10 + 0.8 * 180} y1={10} x2={10 + 0.8 * 180} y2={100} stroke="#d97706" strokeDasharray="3 3" /><text x={10 + 0.8 * 180 - 30} y={20} fontSize={8} fill="#b45309">80% busy</text><text x={150} y={108} fontSize={7} fill="#64748b">utilisation →</text></>, 'Response time rises steeply above 80% utilisation')
    case 'spike': { const ys = [0.4, 0.42, 0.38, 0.41, 0.4, 0.43, 0.39, 0.41, 0.85, 0.42, 0.4, 0.41]; return svg(<>{axes}{line(ys.map((y, i) => `${10 + (i / 11) * 180},${100 - y * 85}`).join(' '))}<line x1={10} y1={100 - 0.6 * 85} x2={190} y2={100 - 0.6 * 85} stroke="#94a3b8" strokeDasharray="4 3" /><circle cx={10 + (8 / 11) * 180} cy={100 - 0.85 * 85} r={5} fill="#0f2747" /><text x={14} y={100 - 0.6 * 85 - 3} fontSize={7.5} fill="#64748b">3σ limit</text></>, 'Anomaly above the control limit') }
    case 'two-dist': return svg(<>{axes}{line(P((x) => Math.exp(-((x - 0.38) ** 2) / 0.02)), '#94a3b8')}{line(P((x) => Math.exp(-((x - 0.6) ** 2) / 0.02)))}<text x={40} y={20} fontSize={8} fill="#64748b">training</text><text x={130} y={20} fontSize={8} fill="#2563eb">today</text></>, 'Training vs current distribution — drift')
    case 'pareto': { const b = [0.95, 0.62, 0.45, 0.3, 0.2, 0.12, 0.08]; let c = 0; const tot = b.reduce((a, x) => a + x, 0); const cum = b.map((x) => (c += x) / tot); return svg(<>{axes}{b.map((h, i) => <rect key={i} x={14 + i * 25} y={100 - h * 80} width={20} height={h * 80} fill="#2563eb" rx={1} />)}{line(cum.map((y, i) => `${24 + i * 25},${100 - y * 85}`).join(' '), '#0f2747')}<line x1={10} y1={100 - 0.8 * 85} x2={190} y2={100 - 0.8 * 85} stroke="#94a3b8" strokeDasharray="3 3" /><text x={150} y={100 - 0.8 * 85 - 3} fontSize={7.5} fill="#64748b">80%</text></>, 'Pareto bars with cumulative line') }
    case 'tornado': return svg(<>{[[0.9, 'Benefit value'], [0.6, 'Build cost'], [0.45, 'Delay'], [0.3, 'Discount rate']].map(([w, l], i) => <g key={l as string}><rect x={100 - (w as number) * 70} y={14 + i * 22} width={(w as number) * 140} height={14} fill="#86b6ef" rx={2} /><text x={100} y={24 + i * 22} textAnchor="middle" fontSize={8} fill="#0f2747">{l as string}</text></g>)}<line x1={100} y1={8} x2={100} y2={104} stroke="#475569" /></>, 'Tornado chart: widest bar = biggest driver')
    case 'glide': { const act = [0, 0.08, 0.15, 0.2, 0.3, 0.38, 0.42, 0.5, 0.55, 0.6, 0.66, 0.7]; return svg(<>{axes}{line(P((x) => x * 0.95), '#94a3b8', '5 4')}{line(act.map((y, i) => `${10 + (i / 11) * 120},${100 - y * 85}`).join(' '))}<line x1={10} y1={100 - 0.95 * 85} x2={190} y2={100 - 0.95 * 85} stroke="#94a3b8" strokeDasharray="2 3" /><text x={150} y={100 - 0.95 * 85 - 3} fontSize={7.5} fill="#64748b">target</text><text x={14} y={108} fontSize={7.5} fill="#64748b">baseline</text></>, 'Actual progress against the planned glide path') }
    case 'cashflow': { const f = [-0.8, 0.15, 0.3, 0.4, 0.45, 0.45]; let c = 0; return svg(<>{axes}<line x1={10} y1={60} x2={190} y2={60} stroke="#94a3b8" />{f.map((v, i) => <rect key={i} x={18 + i * 29} y={v >= 0 ? 60 - v * 50 : 60} width={20} height={Math.abs(v) * 50} fill={v >= 0 ? '#2563eb' : '#0f2747'} rx={1} />)}{line(f.map((v, i) => { c += v; return `${28 + i * 29},${60 - c * 50}` }).join(' '), '#d97706')}<text x={14} y={20} fontSize={7.5} fill="#b45309">cumulative → payback</text></>, 'Cash flows: investment first, then returns; cumulative line crosses zero at payback') }
    case 'forecast': { const a = [0.3, 0.33, 0.36, 0.4, 0.42, 0.47, 0.5, 0.55]; return svg(<>{axes}{line(a.map((y, i) => `${10 + i * 15},${100 - y * 85}`).join(' '))}{line([7, 8, 9, 10, 11, 12].map((i, k) => `${10 + i * 15},${100 - (0.55 + k * 0.05) * 85}`).join(' '), '#0f2747', '5 4')}<line x1={10} y1={100 - 0.8 * 85} x2={190} y2={100 - 0.8 * 85} stroke="#d97706" strokeDasharray="3 3" /><text x={150} y={100 - 0.8 * 85 - 3} fontSize={7.5} fill="#b45309">limit</text></>, 'History and dashed forecast reaching a limit') }
    case 'breakeven': return svg(<>{axes}{line(P((x) => x * 0.95))}{line(P((x) => 0.3 + x * 0.45), '#0f2747')}<line x1={10} y1={100 - 0.3 * 85} x2={190} y2={100 - 0.3 * 85} stroke="#94a3b8" strokeDasharray="3 3" /><circle cx={10 + 0.6 * 180} cy={100 - 0.57 * 85} r={4} fill="#d97706" /><text x={10 + 0.6 * 180 + 6} y={100 - 0.57 * 85 + 10} fontSize={7.5} fill="#b45309">break-even</text><text x={140} y={20} fontSize={7.5} fill="#2563eb">revenue</text><text x={14} y={100 - 0.3 * 85 - 3} fontSize={7.5} fill="#64748b">fixed cost</text></>, 'Revenue and total cost lines crossing at break-even')
    case 'horizons': return svg(<>{axes}{[[0.15, '#0f2747', 'H1'], [0.45, '#2563eb', 'H2'], [0.75, '#86b6ef', 'H3']].map(([m, c, l]) => <g key={l as string}>{line(P((x) => 0.85 / (1 + Math.exp(-14 * (x - (m as number))))), c as string)}<text x={10 + (m as number) * 180 + 6} y={100 - 0.5 * 85} fontSize={8} fill={c as string} fontWeight={600}>{l as string}</text></g>)}<text x={14} y={108} fontSize={7} fill="#64748b">time →</text></>, 'Three overlapping S-curves: core, emerging, future')
    case 'heat': return svg(<>{Array.from({ length: 25 }, (_, i) => { const L = 5 - Math.floor(i / 5), I = (i % 5) + 1, s = L * I; return <rect key={i} x={40 + (i % 5) * 26} y={6 + Math.floor(i / 5) * 19} width={24} height={17} rx={2} fill={s >= 20 ? '#fecaca' : s >= 12 ? '#fde68a' : '#dcfce7'} /> })}<text x={14} y={56} fontSize={8} fill="#64748b">likelihood</text><text x={100} y={108} fontSize={8} fill="#64748b" textAnchor="middle">impact →</text></>, '5 by 5 likelihood × impact heat map')
  }
}

export default function ReferencePage() {
  const [q, setQ] = useState('')
  const [cat, setCat] = useState<Cat | 'All'>('All')
  const list = useMemo(() => REFS.filter((r) => (cat === 'All' || r.cat === cat) && (!q || `${r.name} ${r.core} ${r.when}`.toLowerCase().includes(q.toLowerCase()))), [q, cat])
  return (
    <>
      <PageHeader title="Reference library" subtitle={`${REFS.length} frameworks, techniques and concepts — each with a small picture, the core idea in plain words, and where CTO360 uses it`} />
      <div className="flex flex-wrap items-center gap-2 mb-3">
        <label className="relative"><Search size={14} className="absolute left-2 top-1/2 -translate-y-1/2 text-ink-4" aria-hidden />
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search (e.g. risk, adoption, cost)…" className="pl-7 pr-2 py-1.5 text-sm border border-slate-300 rounded-lg w-72 max-w-full" aria-label="Search the reference library" /></label>
        <span className="text-xs text-ink-3">{list.length} shown · green link = applied in CTO360 · <Link to="/team/frameworks" className="text-brand-600 font-semibold hover:underline">Which framework when →</Link></span>
      </div>
      <div className="flex flex-wrap gap-1.5 mb-5">{(['All', ...CATS] as (Cat | 'All')[]).map((c) => (
        <button key={c} onClick={() => setCat(c)} aria-pressed={cat === c} className={`text-xs rounded-full border px-2.5 py-1 ${cat === c ? 'bg-brand-600 text-white border-brand-600' : 'bg-white text-ink-2 border-line hover:bg-slate-50'}`}>{c}{c !== 'All' && <span className="opacity-70"> {REFS.filter((r) => r.cat === c).length}</span>}</button>
      ))}</div>
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{list.map((r) => (
        <article key={r.name} className="bg-surface rounded-xl border border-line p-4 flex flex-col">
          <div className="flex items-start justify-between gap-2 mb-2"><h3 className="font-semibold text-ink leading-snug">{r.name}</h3><span className="text-[10px] uppercase tracking-wide text-ink-3 shrink-0 mt-0.5">{r.cat}</span></div>
          <div className="mb-3"><Visual v={r.vis} /></div>
          <p className="text-sm text-ink-2 leading-relaxed">{r.core}</p>
          <p className="text-xs text-ink-3 mt-2"><b className="text-ink-2">Use it to answer:</b> {r.when}</p>
          <div className="mt-auto pt-3">{r.applied
            ? <Link to={r.applied[0]} className="inline-flex items-center gap-1 text-xs font-semibold rounded-md border border-green-200 bg-success-bg text-success-text px-2 py-1 hover:underline">Applied in CTO360 · {r.applied[1]}<ArrowRight size={12} /></Link>
            : <span className="text-xs text-ink-3 rounded-md border border-line bg-slate-50 px-2 py-1">Reference · not built as a screen</span>}</div>
        </article>
      ))}</div>
      {list.length === 0 && <p className="text-sm text-ink-3">No match — try another word.</p>}
      <p className="text-xs text-ink-3 mt-6">Simplified explanations for a mixed audience. Diagrams are illustrative, not data. Source list: the course syllabus, the 20 key concepts and the consolidated CTO framework library (project document "Syllabus & Frameworks").</p>
    </>
  )
}
